<?php

namespace App\Services;

class XmlTeamScoreApiService
{
    /*Returns The Latest Sports News*/
    public function mlbFeeds()
    {

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'http://sw5feed.xmlteam.com/sportsml/files/2020/07/31/baseball/l.mlb.com/event-summary/xt.tsf.20200731214410-box-20200100-mid-event.xml');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        $post = array(
            'Username' => '',
            'Password' => '',
        );
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

        $headers   = array();
        $headers[] = 'Accept: application/xml';
        $headers[] = 'Authorization: Basic YmV0c2F2aW9yOjRkNHQxNA==';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);

        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }
}
